# Logging levels
logging.level.service=INFO
logging.level.siri=INFO
logging.level.model.serviceJourney=INFO
logging.level.util=INFO
logging.level.subscription=INFO

# API base URLs
avinor.api.base-url-xmlfeed=https://asrv.avinor.no/XmlFeed/v1.0
avinor.api.base-url-airport-names=https://asrv.avinor.no/airportNames/v1.0

# NeTEx data download URLs
netex.data.url=https://storage.googleapis.com/marduk-dev/outbound/netex/rb_avi-aggregated-netex.zip
stop.place.data.url=https://storage.googleapis.com/marduk-dev/tiamat/Airports_latest.zip

