apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-application
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gibil.common.labels" . | nindent 4 }}
data:
  application.properties: |-
    # Spring Boot
    avinor.api.base-url-xmlfeed=https://asrv.avinor.no/XmlFeed/v1.0
    avinor.api.base-url-airport-names=https://asrv.avinor.no/airportNames/v1.0
    entur.api.base-url-stop-places=https://api.entur.io/stop-places/v1/read/stop-places

    # Netex data file path 
    org.gibil.extime.data-file=/tmp/netex_data
    
    # Actuator
    management.server.port=8080
    management.endpoints.enabled-by-default=true
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.probes.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoints.web.exposure.include=health,info

    # Logging
    logging.level.root={{ .Values.configMap.LOG_LEVEL }}