common:
  app: gibil
  shortname: gibil
  team: ror
  service:
    externalPort: 80
    internalPort: 8080
  container:
    image: <+artifacts.primary.image>
    imagePullPolicy: Always
    cpu: 2
    memory: 2560
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    volumeMounts:
      - mountPath: /etc/application-config
        name: application-config
        readOnly: true
    volumes:
      - configMap:
            defaultMode: 420
            name: gibil-application
        name: application-config
    probes:
      startupProbe:
        enabled: true
      readinessProbe:
        path: /actuator/health/readiness
      livenessProbe:
        path: /actuator/health/liveness
  configmap:
    data:
      JDK_JAVA_OPTIONS: -server -Xmx512m -XX:ActiveProcessorCount=1 -Dspring.config.additional-location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8
      TZ: Europe/Oslo
    enabled: true
    toEnv: true