common:
  configmap:
    data:
      NETEX_DATA_URL: https://storage.googleapis.com/marduk-production/outbound/netex/rb_avi-aggregated-netex.zip
  env: prd
  ingress:
    trafficType: public
    host: gibil.entur.io
  container:
    forceReplicas: 1

configMap:
  LOG_LEVEL: INFO

cronJob:
    gcpProject: entur-prod-gcp2