common:
  configmap:
    data:
      NETEX_DATA_URL: https://storage.googleapis.com/marduk-dev/outbound/netex/rb_avi-aggregated-netex.zip
      STOP_PLACE_DATA_URL: https://storage.googleapis.com/marduk-dev/tiamat/Airports_latest.zip
  env: dev
  ingress:
    trafficType: public
    host: gibil.dev.entur.io
  replicas: 1

configMap:
  LOG_LEVEL: DEBUG

cronJob:
  gcpProject: entur-dev-gcp2
  slackUrl: ror-dev-slack-url