common:
  configmap:
    data:
      NETEX_DATA_URL: https://storage.googleapis.com/marduk-test/outbound/netex/rb_avi-aggregated-netex.zip
      STOP_PLACE_DATA_URL: https://storage.googleapis.com/marduk-test/tiamat/Airports_latest.zip
  env: tst
  ingress:
    trafficType: public
    host: gibil.staging.entur.io
  replicas: 1

configMap:
  LOG_LEVEL: INFO

cronJob:
  gcpProject: entur-test-gcp2
  slackUrl: ror-staging-slack-url