common:
  configmap:
    data:
      NETEX_DATA_URL: https://storage.googleapis.com/marduk-dev/outbound/netex/rb_avi-aggregated-netex.zip
  env: dev
  ingress:
    enabled: true
    trafficType: public
    host: gibil.dev.entur.io
  replicas: 1

configMap:
  LOG_LEVEL: DEBUG

cronJob:
  gcpProject: entur-dev-gcp2