common:
  configmap:
    data:
      NETEX_DATA_URL: https://storage.googleapis.com/marduk-production/outbound/netex/rb_avi-aggregated-netex.zip
  env: prd
  ingress:
    enabled: false
    trafficType: public
    host: gibil.entur.io
  replicas: 1
  container:
    replicas: 1
    maxReplicas: 2

configMap:
  LOG_LEVEL: INFO

cronJob:
    gcpProject: entur-prod-gcp2